### ISSUE TITLE
安装cat2执行mvn cat:install报错，请问怎么解决

### ISSUE THREAD

**Issue by H37927** [unidal/cat2#77]
安装cat2执行mvn cat:install报错，请问怎么解决

[ERROR] No plugin found for prefix 'cat' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/root/.m2/repository), central (http://repo1.maven.org/maven2), unidal.releases (http://unidal.org/nexus/content/repositories/releases/)]

**Comment by qmwu2000** [comment]
cat2一直在开发中，还没有完全ready，谢谢！

请先用dianping/cat

发自我的 iPhone

**Comment by H37927** [comment]
哦，好的，支持CAT
